---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoom-deploy
  namespace: kubedoom
  labels:
    app: kd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kd-app
  strategy:
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: kd-app 
    spec:    
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - image: storaxdev/kubedoom:0.5.0
        name: kubedoom-app
        ports:
        - containerPort: 5900
