---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tst-rset
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app    
    spec:    
      containers:
      - image: nginx:1.12
        name: nginx
        ports:
        - containerPort: 80
